apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: landscape
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: platformnow/landscape
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: guests
  lifecycle: experimental