version: '3'
services:
  db:
    image: docker.io/bitnami/postgresql:12
    volumes:
      - 'db_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=postgres
    ports:
      - "5432:5432"
    networks:
        - landscape-network
  backend:
    image: landscape-backend:latest
    restart: always
    ports:
      - "7007:7007"
    environment:
      - POSTGRES_SERVICE_HOST=db
      - POSTGRES_SERVICE_PORT=5432
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - landscape-network
  frontend:
    image: landscape-frontend:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=landscape-backend
    networks:
      - landscape-network
networks:
  landscape-network:
volumes:
  db_data:
    driver: local
